# Site settings
title: Big Johnson Construction
email: team@variantstudios.com
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.bjcsteel.com" # the base hostname & protocol for your site
#timezone: America/Denver
version: "3.2.1" # the version of jekyll

#CloudCannon defaults
uploads_dir: "assets/images"

# Gems for plugins
gems:
  - jekyll-paginate-v2 # Needed to add paginate on Jekyll ver 3+
  - jekyll-sitemap # Simple jekyll plugin that creates a sitemap.xml file and you can exclude files by adding 'sitemap:false' to the frontmatter of any file(s).

# Permalinks
permalink: pretty

# Pagination V2 Settings: https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
pagination:
  enabled: true
  per_page: 4
  permalink: '/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'completion_date'
  sort_reverse: true
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: true
  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'projects'


#Collections
collections:
  projects:
    output: true

defaults:
  -
    scope:
      type: projects
    values:
      layout: project
    _comments:
      thumbnail_image_path: "The image should be a jpg scaled and cropped to 320px wide by 230px tall."
      large_image_path: "The image should be a jpg scaled and cropped to 850px wide by 600px tall."

# Cloudinary URL - something like: https://res.cloudinary.com/domain-com/
cloudinaryurl: ""

# typekit - Because we all need nice type faces.
typekit: "des8ryp"

# Google Analytics - What site isn't using it?!
google_analytics_tracking_id: "UA-33015432-12"

exclude: ["readme.md", "vendor","node_modules","package.json", "package-lock.json","Gemfile","gulpfile.js","*.scss"]